# Generated by Django 3.2.9 on 2021-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvmaze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
