# Generated by Django 3.2.9 on 2021-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvmaze', '0002_alter_filmes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
